# Generated by Django 2.1.4 on 2018-12-25 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmi_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bmi',
            name='bmi_value',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
